Repository ucloud/terraform-provider-ucloud, pull requests merged in 2019-07, with the labels that each got.

#38 add isolation group
  CHANGELOG.md
  go.mod
  go.sum
  ucloud/config.go
  ucloud/import_isolation_group_test.go
  ucloud/provider.go
  ucloud/resource_ucloud_instance.go
  ucloud/resource_ucloud_instance_test.go
  ucloud/resource_ucloud_isolation_group.go
  ucloud/resource_ucloud_isolation_group_test.go
  ucloud/service_ucloud_uhost.go
  ucloud/types.go
  ucloud/validators.go
  vendor/github.com/ucloud/ucloud-sdk-go/services/uhost/create_isolation_group.go
  vendor/github.com/ucloud/ucloud-sdk-go/services/uhost/create_uhost_instance.go
  vendor/github.com/ucloud/ucloud-sdk-go/services/uhost/delete_isolation_group.go
  vendor/github.com/ucloud/ucloud-sdk-go/services/uhost/describe_isolation_group.go
  vendor/github.com/ucloud/ucloud-sdk-go/services/uhost/leave_isolation_group.go
  vendor/github.com/ucloud/ucloud-sdk-go/services/uhost/types_isolation_group.go
  vendor/github.com/ucloud/ucloud-sdk-go/services/uhost/types_spread_info.go
  vendor/github.com/ucloud/ucloud-sdk-go/ucloud/auth/credential.go
  vendor/github.com/ucloud/ucloud-sdk-go/ucloud/request/encoder.go
  vendor/github.com/ucloud/ucloud-sdk-go/ucloud/version/version.go
  vendor/modules.txt
  website/docs/d/images.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/isolation_group.html.markdown
  website/ucloud.erb
Labels: dependencies, documentation, size/XL

#39 delete redundant example
  examples/test/main.tf
Labels: size/S

#40 docs: Format inline codes in docs to canonical format
  website/docs/d/db_instances.html.markdown
  website/docs/d/disks.html.markdown
  website/docs/d/eips.html.markdown
  website/docs/d/images.html.markdown
  website/docs/d/instances.html.markdown
  website/docs/d/lb_attachments.html.markdown
  website/docs/d/lb_listeners.html.markdown
  website/docs/d/lb_rules.html.markdown
  website/docs/d/lb_ssls.html.markdown
  website/docs/d/lbs.html.markdown
  website/docs/d/projects.html.markdown
  website/docs/d/security_groups.html.markdown
  website/docs/d/subnets.html.markdown
  website/docs/d/vpcs.html.markdown
  website/docs/d/zones.html.markdown
  website/docs/index.html.markdown
  website/docs/r/disk.html.markdown
  website/docs/r/eip.html.markdown
  website/docs/r/eip_association.html.markdown
  website/docs/r/instance.html.markdown
  website/docs/r/isolation_group.html.markdown
  website/docs/r/lb.html.markdown
  website/docs/r/lb_attachment.html.markdown
  website/docs/r/lb_listener.html.markdown
  website/docs/r/lb_rule.html.markdown
  website/docs/r/lb_ssl_attachment.html.markdown
  website/docs/r/memcache_instance.markdown
  website/docs/r/redis_instance.markdown
  website/docs/r/security_group.html.markdown
  website/docs/r/subnet.html.markdown
  website/docs/r/udpn_connection.html.markdown
  website/docs/r/vpc.html.markdown
  website/docs/r/vpc_peering_connection.html.markdown
Labels: documentation, good first issue, size/XL

#41 fix WaitForState function problem
  CHANGELOG.md
  ucloud/config.go
  ucloud/resource_ucloud_disk.go
  ucloud/resource_ucloud_instance.go
  ucloud/utils.go
Labels: size/S
