Repository ucloud/terraform-provider-ucloud, pull requests merged in 2019-03, with the labels that each got.

#13 update CHANGELOG
  CHANGELOG.md
Labels: size/XS

#15 add default root password of instance & fix validate disk import
  CHANGELOG.md
  ucloud/consts.go
  ucloud/resource_ucloud_db_instance.go
  ucloud/resource_ucloud_instance.go
  ucloud/validators.go
  website/docs/r/instance.html.markdown
Labels: documentation, size/M

#18 fix lb import && update db password to optional
  CHANGELOG.md
  ucloud/consts.go
  ucloud/import_ucloud_lb_test.go
  ucloud/resource_ucloud_db_instance.go
  ucloud/resource_ucloud_instance.go
  ucloud/resource_ucloud_lb.go
  website/docs/r/db_instance.html.markdown
  website/docs/r/lb.html.markdown
Labels: documentation, size/M

#19 update CHANGELOG
  CHANGELOG.md
Labels: size/S

#20 website: Fix broken filename for lb_ssl resource
  website/docs/r/lb_ssl.html.markdown
Labels: documentation, size/XS

#21 fix lb import & add lb import test
  CHANGELOG.md
  scripts/changelog-links.sh
  ucloud/import_ucloud_lb_attachment_test.go
  ucloud/import_ucloud_lb_listener_test.go
  ucloud/import_ucloud_lb_rule_test.go
  ucloud/resource_ucloud_lb_attachment.go
  ucloud/resource_ucloud_lb_listener.go
  ucloud/resource_ucloud_lb_rule.go
  ucloud/service_ucloud_ulb.go
Labels: size/XL

#22 shorten waiting time and update states
  CHANGELOG.md
  ucloud/resource_ucloud_db_instance.go
  ucloud/resource_ucloud_disk.go
  ucloud/resource_ucloud_disk_attachment.go
  ucloud/resource_ucloud_eip.go
  ucloud/resource_ucloud_lb_attachment.go
  ucloud/resource_ucloud_lb_listener.go
Labels: size/M
