Repository ucloud/terraform-provider-ucloud, pull requests merged in 2020-03, with the labels that each got.

#60 Update instances.html.markdown
  website/docs/d/instances.html.markdown
Labels: documentation, enhancement, size/XS

#61 add high frequency instance type and update datasource
  CHANGELOG.md
  examples/web-server/main.tf
  ucloud/config.go
  ucloud/data_source_ucloud_db_instances.go
  ucloud/data_source_ucloud_disks.go
  ucloud/data_source_ucloud_eips.go
  ucloud/data_source_ucloud_images.go
  ucloud/data_source_ucloud_instances.go
  ucloud/data_source_ucloud_lb_attachments.go
  ucloud/data_source_ucloud_lb_listeners.go
  ucloud/data_source_ucloud_lb_rules.go
  ucloud/data_source_ucloud_lb_ssls.go
  ucloud/data_source_ucloud_lbs.go
  ucloud/data_source_ucloud_nat_gateways.go
  ucloud/data_source_ucloud_security_groups.go
  ucloud/data_source_ucloud_subnets.go
  ucloud/data_source_ucloud_vpcs.go
  ucloud/data_source_ucloud_vpn_connections.go
  ucloud/data_source_ucloud_vpn_customer_gateways.go
  ucloud/data_source_ucloud_vpn_gateways.go
  ucloud/resource_ucloud_instance.go
  ucloud/types.go
  website/docs/appendix/instance_type.html.markdown
  website/docs/d/db_instances.html.markdown
  website/docs/d/disks.html.markdown
  website/docs/d/eips.html.markdown
  website/docs/d/images.html.markdown
  website/docs/d/instances.html.markdown
  website/docs/d/lb_attachments.html.markdown
  website/docs/d/lb_listeners.html.markdown
  website/docs/d/lb_rules.html.markdown
  website/docs/d/lb_ssls.html.markdown
  website/docs/d/lbs.html.markdown
  website/docs/d/nat_gateways.html.markdown
  website/docs/d/security_groups.html.markdown
  website/docs/d/subnets.html.markdown
  website/docs/d/vpcs.html.markdown
  website/docs/d/vpn_connections.html.markdown
  website/docs/d/vpn_customer_gateways.html.markdown
  website/docs/d/vpn_gateways.html.markdown
  website/docs/index.html.markdown
  website/docs/r/lb_attachment.html.markdown
  website/docs/r/lb_listener.html.markdown
  website/ucloud.erb
Labels: documentation, size/XL

#63 Update subnet.html.markdown
  website/docs/r/subnet.html.markdown
Labels: documentation, size/XS
